############################################################
# Dockerfile to build Kibana v 5.6.3
############################################################

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.6.3

MAINTAINER Stanislav WEB "stanisov@gmail.com"

# Add your kibana plugins setup here
#RUN kibana-plugin install x-pack