############################################################
# Dockerfile to build Elasticsearch v 5.6.3
############################################################

FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.3

MAINTAINER Stanislav WEB "stanisov@gmail.com"

# Add your elasticsearch plugins setup here
#RUN elasticsearch-plugin install x-pack