############################################################
# Dockerfile to build Logstash v 5.6.3
############################################################

FROM docker.elastic.co/logstash/logstash:5.6.3

MAINTAINER Stanislav WEB "stanisov@gmail.com"

# Add your logstash plugins setup here
RUN logstash-plugin install x-pack